# See https://pre-commit.com/ for usage and config
# pre-commit install
# need commit-msg hook for commitzen
# pre-commit install --hook-type commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-toml
    -   id: check-yaml
    -   id: no-commit-to-branch

-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        stages: [pre-commit]
        language: system
        entry: poetry run ruff format
        types: [python]

    -   id: mdformat
        name: mdformat
        stages: [pre-commit]
        language: system
        entry: poetry run mdformat --number
        types: [markdown]

    -   id: pytest
        name: pytest
        stages: [pre-commit]
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false
